---
- name: installing packages on Redhat and Ubuntu
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
  - name: installing httpd on Redhat
    yum:
        name: httpd
        state: installed
    when: ansible_os_family == "RedHat"
    notify: Start httpd services on RedHat

  - name: Install apache on ubuntu
    apt:
        name: apache2
        state: present
    when: ansible_os_family == "Debian"

  - name: Copying index.html
    copy:
        src: /home/ansadmin/playbook/index.html
        dest: /var/www/html

    handlers:

  - name: Starting apache on ubuntu
    service:
        name: apache2
        state: started
    when: ansible_os_family == "Debian"

  - name: Start httpd service on RedHat
    service:
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
