---
- name: playbook to install apache tomcat
  hosts: webservers
  become: true
  gather_facts: yes

  vars_files:
    - tomcat_vars.yml
  tasks:
  - name: install java-1.8*
    yum:
      name: java
      state: installed

  - name: downloading tomcat packages
    get_url:
      url: "{{ tomcat_url }}"
      dest: /opt
      mode: 0755

  - name: extract packages
    unarchive:
      src: /opt/{{ tomcat_package }}.tar.gz
      dest: /opt
      remote_src: yes

  - name: change permissions on apache-tomcat file
    file:
      path: /opt/{{ tomcat_package }}
      mode: 0755
      recurse: yes

  - name: creating link file for tomcat {{item.tomcat_script}}
    file:
      src: /opt/{{ tomcat_package }}/bin/{{item.tomcat_script}}
      dest: /usr/local/bin/{{item.tomcat_command}}
      state: link
    loop:
      - { tomcat_script: 'startup.sh', tomcat_command: tomcatup}
      - { tomcat_script: 'shutdown.sh', tomcat_command: tomcatdown}

  - name: Start the services
    command: nohup ./startup.sh
    args:
      chdir: /opt/{{ tomcat_package }}/bin

